services:
  postgres:
    image: postgres:16
    container_name: de_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../../infra/postgres/init:/docker-entrypoint-initdb.d

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: de_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: de_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  n8n:
    image: n8nio/n8n:latest
    container_name: de_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  pg_data:
  n8n_data:


# Optional: Kafka UI
kafdrop:
  image: obsidiandynamics/kafdrop:latest
  container_name: de_kafdrop
  depends_on:
    - kafka
  ports:
    - "9000:9000"
  environment:
    KAFKA_BROKERCONNECT: "kafka:29092"
    JVM_OPTS: "-Xms32M -Xmx128M"


kafka_init:
  image: confluentinc/cp-kafka:7.6.1
  container_name: de_kafka_init
  depends_on:
    - kafka
  entrypoint: ["/bin/bash","-lc"]
  command: >
    "
    echo 'Waiting for Kafka...' &&
    cub kafka-ready -b kafka:29092 1 40 &&
    kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists
      --topic demo.posts --partitions 1 --replication-factor 1 &&
    echo 'Topic ensured: demo.posts'
    "
  restart: "no"

kafka_consumer:
  build:
    context: ../../apps/kafka_consumer
  container_name: de_kafka_consumer
  depends_on:
    - kafka_init
    - postgres
  environment:
    KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
    KAFKA_TOPIC: "demo.posts"
    KAFKA_GROUP_ID: "ods-loader"
    PGHOST: "postgres"
    PGPORT: "5432"
    PGDATABASE: ${POSTGRES_DB}
    PGUSER: ${POSTGRES_USER}
    PGPASSWORD: ${POSTGRES_PASSWORD}
  restart: unless-stopped

kafka_producer:
  build:
    context: ../../apps/kafka_producer
  container_name: de_kafka_producer
  depends_on:
    - kafka_init
  environment:
    KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
    KAFKA_TOPIC: "demo.posts"
    PRODUCE_COUNT: "25"
  restart: "no"
